apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flashlight-model-store-pvc
  namespace: agami
  labels:
    app: flashlight
    component: model-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path