apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facial-recognition-model-store-pvc
  namespace: agami
  labels:
    app: face-liveness
    component: model-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
