apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  # K3s 기본 storageClass 인 local-path 가 자동 선택됨 (StorageClassName 미지정).
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
