apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha-frontend
  labels:
    app: captcha-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captcha-frontend
  template:
    metadata:
      labels:
        app: captcha-frontend
    spec:
      containers:
        - name: web
          image: HARBOR_URL/agami/captcha-frontend:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
