apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: context-emotion-api
  namespace: argocd
  labels:
    app: context-emotion-api
    team: agami
spec:
  project: default

  source:
    repoURL: https://github.com/ai-denied/agami_mlops.git
    targetRevision: main
    path: manifests/context-emotion-api

  destination:
    server: https://kubernetes.default.svc
    namespace: agami

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
